name: 🐛 Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the information requested. Issues that do not follow this format are likely to stall.
  - type: textarea
    id: description
    attributes:
      label: 🐛 What issue do you have?
      description: Please provide a clear and concise description of what the bug is. Include screenshots if needed.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Desktop Node Version
      description: What is the latest version of desktop node that this issue reproduces on? 
      placeholder: ex. 0.2.14
    validations:
      required: true
  - type: input
    id: task
    attributes:
      label: Task ID
      description: What is the task ID that this issue happens on?
      placeholder: ex. 4JDWH29ZGusREiMsGRhwBa5cWmYt93osXpeD3vKKYb6V
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
    validations:
      required: true
